name: Validate JSON

on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate JSON files
        run: |
          find . -name "*.json" -type f -print0 | while IFS= read -r -d '' file; do
            echo "Validating $file"
            cat "$file" | jq . > /dev/null || { echo "Error: $file is not valid JSON"; exit 1; }
          done
          echo "All JSON files are valid."
